name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Google Cloud SDK
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Authenticate Docker with Artifact Registry (GAR)
    - name: Authenticate Docker with Artifact Registry
      run: |
        gcloud auth configure-docker europe-west6-docker.pkg.dev

    # Generate a unique image tag based on timestamp
    - name: Set Image Tag
      run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    # Build Docker image with both a version tag and latest tag
    - name: Build Docker image
      run: |
        docker build -t europe-west6-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-marketing-generator-ari/ai-marketing-generator:$IMAGE_TAG .
        docker tag europe-west6-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-marketing-generator-ari/ai-marketing-generator:$IMAGE_TAG \
                  europe-west6-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-marketing-generator-ari/ai-marketing-generator:latest

    # Push both versioned and latest Docker images to Artifact Registry
    - name: Push Docker image to Artifact Registry
      run: |
        docker push europe-west6-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-marketing-generator-ari/ai-marketing-generator:$IMAGE_TAG
        docker push europe-west6-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-marketing-generator-ari/ai-marketing-generator:latest

    # Deploy to Google Cloud Run, ensuring it listens on port 5000
    - name: Deploy to Google Cloud Run
      run: |
        gcloud components install beta --quiet
        gcloud beta run deploy ${{ secrets.GCP_SERVICE }} \
          --region europe-west6 \
          --execution-environment gen2 \
          --image europe-west6-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-marketing-generator-ari/ai-marketing-generator:$IMAGE_TAG \
          --add-volume name=my-gcs-volume,type=cloud-storage,bucket=ai-marketing-generator-storage \
          --add-volume-mount volume=my-gcs-volume,mount-path=/mnt/database/ \
          --memory 512Mi \
          --platform managed \
          --port 5000 \
          --service-account ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }} \
          --set-env-vars HF_API_KEY=${{ secrets.HF_API_KEY }},CSV_DATABASE_PATH=/mnt/database/final_product_database_with_unique_names.csv \
          --quiet
